export const EmployeeData=[
    {
        id:1,
        firstName:'Mark',
        lastName:'sune',
        age:20
    },
    {
        id:2,
        firstName:'Issu',
        lastName:'sune',
        age:27
    },
    {
        id:3,
        firstName:'kaya',
        lastName:'sune',
        age:25
    }
]
